version: '3.7'
services:
  tomcat-web-practice:
    container_name: tomcat_practice
    #image: tomcat:9.0.30-jdk8-openjdk
    build: .
    ports: 
      - "8888:8080"
      - "8819:8889" # As 2 services are exposed, so 2 ports are open for access to Docker host 
    expose:
      - "8888"
      - "8889"
    volumes:
      - type: volume
        source: practice_vol
        target: /usr/local/tomcat
    #image: hdbhandari/tomcat_practice:1.1

volumes: 
  practice_vol:

# nano /usr/local/tomcat/webapps/host-manager/META-INF/context.xml
# nano /usr/local/tomcat/conf/tomcat-users.xml

